import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :digital_oil_sticker, DigitalOilStickerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Explicit, not inherited: whether stack traces and source excerpts reach the
  # internet is not something to leave to a framework default.
  debug_errors: false,
  code_reloader: false

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :digital_oil_sticker, DigitalOilStickerWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # Fly's platform checks reach the machine over plain HTTP on the internal
      # port, so redirecting them to https makes the machine look unhealthy and
      # it gets stopped. HSTS still applies to every other path.
      paths: ["/health", "/ready", "/version"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
