import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :digital_oil_sticker, DigitalOilStickerWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # Explicit, not inherited: whether stack traces and source excerpts reach the
  # internet is not something to leave to a framework default.
  debug_errors: false,
  code_reloader: false

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :digital_oil_sticker, DigitalOilStickerWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # Fly's platform checks reach the machine over plain HTTP on the internal
      # port, so redirecting them to https makes the machine look unhealthy and
      # it gets stopped. HSTS still applies to every other path.
      #
      # `.well-known/acme-challenge/` is exempt so Let's Encrypt's HTTP-01
      # renewal can reach the challenge token. Redirecting it to https before
      # a certificate exists is the paradox that blocks the certificate.
      paths: ["/health", "/ready", "/version", "/.well-known/acme-challenge/"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# The content security policy is ENFORCED in production.
#
# FR-3's sequence was followed rather than assumed: the policy shipped
# report-only, and a full session plus every route was driven on Chromium 141,
# Gecko 142, WebKit 26, and real Android Chrome 150 on a Lenovo TB125FU. The
# first such run reported 56 violations — every inline style attribute on the
# sticker — which enforcing straight away would have turned into a collapsed
# sticker on a live site. Those moved into CSS, and the sweep now reports zero
# on all four.
#
# Enforcing also activates `frame-ancestors 'none'`, which a browser ignores in
# report-only mode. Until now clickjacking protection rested on
# X-Frame-Options: DENY alone.
config :digital_oil_sticker, DigitalOilStickerWeb.Plugs.SecurityHeaders, enforce: true
