defmodule DigitalOilStickerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :digital_oil_sticker

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # Carries the CSRF token and live_socket_id, and nothing else — asserted by
  # test. `secure` and `max_age` are set explicitly rather than inherited:
  # whether a cookie crosses plain HTTP, and how long it outlives the visit,
  # are not decisions to leave to a default (FR-7).
  @session_options [
    store: :cookie,
    key: "_digital_oil_sticker_key",
    signing_salt: "sN71ocqW",
    same_site: "Lax",
    http_only: true,
    secure: Mix.env() == :prod,
    # Short. There is no account and nothing to stay signed in to; the cookie
    # exists for CSRF and socket identity, so a long life is pure exposure.
    max_age: 60 * 60 * 8
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :digital_oil_sticker,
    gzip: not code_reloading?,
    only: DigitalOilStickerWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :digital_oil_sticker
  end

  # No Phoenix.LiveDashboard.RequestLogger. The generator mounts it
  # unconditionally, which leaves a request-log tap on every production
  # request: anyone who sets the `request_logger` param or cookie starts
  # streaming this server's logs. The dashboard route itself is dev-only, so
  # the plug bought nothing in production and gave away log access (INV-26).
  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # Ahead of the router on purpose: a response that never reaches a pipeline —
  # a 404, a parser error — still needs the header set.
  plug DigitalOilStickerWeb.Plugs.SecurityHeaders

  plug DigitalOilStickerWeb.Router
end
