#!/usr/bin/env node
// Writes docs/governance/ROADMAP_LEDGER.md from planning/state.json (server
// returned values only) plus planning/roadmap.yml. Run after apply + verify.

import { loadCatalog } from './lib/catalog.mjs'
import { loadState } from './lib/state.mjs'
import { writeFileAtomic, fail } from './lib/util.mjs'

const catalog = loadCatalog()
const state = loadState()
if (!state.repo || !state.project) fail('no applied state; run apply first')

const msTitle = Object.fromEntries(catalog.milestones.map(m => [m.id, m.title]))
const lines = []
lines.push('# Roadmap ledger')
lines.push('')
lines.push('Mapping of stable roadmap IDs to their GitHub objects. Generated by `scripts/github/write-ledger.mjs` from server-returned values in `planning/state.json` after read-back verification — never hand-edited.')
lines.push('')
lines.push(`- Repository: ${state.repo.url} (${state.repo.visibility})`)
lines.push(`- Project: ${state.project.url} — "${state.project.title}"`)
lines.push(`- Milestones: ${catalog.milestones.map(m => `[${m.id}](${state.repo.url}/milestone/${state.milestones[m.id]?.number})`).join(' · ')}`)
lines.push('')
if (state.statusConfigured?.via === 'manual-required') {
  lines.push(`> Built-in Status options could not be configured via API (${state.statusConfigured.reason ?? 'see PROJECT_MANUAL_SETUP.md'}). See docs/governance/PROJECT_MANUAL_SETUP.md.`)
  lines.push('')
}
lines.push('| Roadmap ID | Issue | Milestone | Parent | Blocked by | Priority | Workstream | Risk | Target | Seq |')
lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |')
for (const i of catalog.issues) {
  const s = state.issues[i.id]
  if (!s?.number) fail(`ledger: ${i.id} missing from state`)
  const parent = i.parent ? `#${state.issues[i.parent]?.number}` : '—'
  const blockers = i.blockedBy.length ? i.blockedBy.map(b => `#${state.issues[b]?.number}`).join(' ') : '—'
  lines.push(`| ${i.id} | [#${s.number}](${s.url}) | ${msTitle[i.milestone]} | ${parent} | ${blockers} | ${i.priority} | ${i.workstream} | ${i.risk || '—'} | ${i.target} | ${i.sequence} |`)
}
lines.push('')
lines.push(`Total: ${catalog.issues.length} issues — ${catalog.issues.filter(i => i.type === 'epic').length} epics, ${catalog.issues.filter(i => i.type === 'child').length} children.`)
writeFileAtomic('docs/governance/ROADMAP_LEDGER.md', lines.join('\n') + '\n')
console.log('wrote docs/governance/ROADMAP_LEDGER.md')
