// Strict-subset YAML parser for planning/roadmap.yml.
// Supported: two-space indentation, maps of scalars, nested maps, lists of maps,
// lists of scalars, plain scalars, double-quoted scalars with \" and \\ escapes,
// full-line comments starting with #. Anything else fails loudly — this file is
// generated by scripts/github/assemble-roadmap.mjs and must stay in the subset.

function parseScalar(raw, where) {
  const s = raw.trim()
  if (s === '') return ''
  if (s.startsWith('"')) {
    if (!s.endsWith('"') || s.length < 2) throw new Error(`${where}: unterminated quoted scalar: ${raw}`)
    return s.slice(1, -1).replace(/\\(["\\])/g, '$1')
  }
  if (/^-?\d+$/.test(s)) return Number(s)
  if (s === 'true') return true
  if (s === 'false') return false
  if (/[#{}[\]&*!|>%@`]/.test(s[0] ?? '')) throw new Error(`${where}: unsupported YAML syntax: ${raw}`)
  return s
}

export function parseYaml(text, name = 'yaml') {
  const lines = text.split('\n')
  let pos = 0

  function indentOf(line) {
    const m = line.match(/^( *)/)
    if (m[1].length % 2 !== 0) throw new Error(`${name}:${pos + 1}: odd indentation`)
    return m[1].length / 2
  }

  function skippable(line) {
    return line.trim() === '' || line.trim().startsWith('#')
  }

  function parseBlock(indent) {
    // Decide list vs map from the first meaningful line.
    while (pos < lines.length && skippable(lines[pos])) pos++
    if (pos >= lines.length) return {}
    const first = lines[pos]
    if (indentOf(first) !== indent) throw new Error(`${name}:${pos + 1}: unexpected indent`)
    return first.trim().startsWith('- ') || first.trim() === '-'
      ? parseList(indent)
      : parseMap(indent)
  }

  function parseMap(indent) {
    const out = {}
    while (pos < lines.length) {
      const line = lines[pos]
      if (skippable(line)) { pos++; continue }
      const ind = indentOf(line)
      if (ind < indent) break
      if (ind > indent) throw new Error(`${name}:${pos + 1}: unexpected deeper indent`)
      const t = line.trim()
      if (t.startsWith('- ')) break
      const ci = t.indexOf(':')
      if (ci < 1) throw new Error(`${name}:${pos + 1}: expected "key: value"`)
      const key = t.slice(0, ci).trim()
      const rest = t.slice(ci + 1)
      pos++
      if (rest.trim() === '') {
        // nested block (map or list) or empty value
        let look = pos
        while (look < lines.length && skippable(lines[look])) look++
        if (look < lines.length && indentOf(lines[look]) > indent) {
          out[key] = parseBlock(indent + 1)
        } else {
          out[key] = ''
        }
      } else {
        out[key] = parseScalar(rest, `${name}:${pos}`)
      }
    }
    return out
  }

  function parseList(indent) {
    const out = []
    while (pos < lines.length) {
      const line = lines[pos]
      if (skippable(line)) { pos++; continue }
      const ind = indentOf(line)
      if (ind < indent) break
      if (ind > indent) throw new Error(`${name}:${pos + 1}: unexpected deeper indent in list`)
      const t = line.trim()
      if (!t.startsWith('- ')) break
      const rest = t.slice(2)
      const ci = rest.indexOf(': ')
      if (ci >= 1 || /^[A-Za-z_][\w-]*:$/.test(rest.trim())) {
        // list item is a map; rewrite the dash line as the first key line
        lines[pos] = ' '.repeat((indent + 1) * 2) + rest
        out.push(parseMap(indent + 1))
      } else {
        pos++
        out.push(parseScalar(rest, `${name}:${pos}`))
      }
    }
    return out
  }

  const doc = parseBlock(0)
  while (pos < lines.length) {
    if (!skippable(lines[pos])) throw new Error(`${name}:${pos + 1}: trailing content outside document`)
    pos++
  }
  return doc
}

export function quote(s) {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
}
